version: 0.0
Resources:
  - deepl-for-slack:
      Type: AWS::Lambda::Function
      Properties:
        Name: "deepl-for-slack"
        Alias: "deeplSlackAlias"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"