version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      
  build:
    commands:
      - echo "Zipping deployment package..."
      
      - zip -r9 ../deepl-for-slack.zip .
      